services:
  db_biblioteca:
    image: postgres:17
    environment:
      POSTGRES_DB: sigesi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - sigesi_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d biblioteca"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sigesi_data:
