services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  db:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - sigesi_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  sigesi-backend:
    image: marcosqf/sigesi-backend:latest
    container_name: sigesi-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    expose:
      - "8080"
    restart: always

  sigesi-frontend:
    image: marcosqf/sigesi-frontend:latest
    container_name: sigesi-frontend
    expose:
      - "80"
    restart: always

  minio:
    image: minio/minio:latest
    container_name: sigesi-minio
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

  notification-service:
    image: marcosqf/sigesi-notifiction-service:latest
    container_name: notification-service
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - .env2

  notification-db:
    image: postgres:16-alpine
    container_name: sigesi-notification-db
    environment:
      - POSTGRES_USER=notif_user
      - POSTGRES_PASSWORD=notif_pass
      - POSTGRES_DB=notifications
    ports:
      - "5433:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: sigesi-rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      restart: unless-stopped
      # networks:
      #   - default
      #   - sigesi-network

volumes:
  sigesi_data:
  minio_data:
  notification_db_data:
  rabbitmq_data:

networks:
  default:
    external: true
