# Generated by Django 5.2.11 on 2026-02-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jazigos', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaveta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('jazigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gavetas', to='jazigos.jazigo')),
                ('ocupante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gavetas', to='pessoas.pessoa')),
            ],
            options={
                'verbose_name': 'gaveta',
                'verbose_name_plural': 'gavetas',
                'ordering': ['numero'],
            },
        ),
    ]
