# Generated by Django 5.2.11 on 2026-02-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluida'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'demanda',
                'verbose_name_plural': 'demandas',
            },
        ),
        migrations.CreateModel(
            name='DemandaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'demanda material',
                'verbose_name_plural': 'demanda materiais',
            },
        ),
    ]
