# Generated by Django 5.2.11 on 2026-02-08 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandas', '0001_initial'),
        ('materiais', '0001_initial'),
        ('solicitacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demanda',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='solicitacoes.solicitacao'),
        ),
        migrations.AddField(
            model_name='demandamaterial',
            name='demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demanda_materiais', to='demandas.demanda'),
        ),
        migrations.AddField(
            model_name='demandamaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demanda_materiais', to='materiais.material'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='materiais',
            field=models.ManyToManyField(blank=True, related_name='demandas', through='demandas.DemandaMaterial', to='materiais.material'),
        ),
        migrations.AddConstraint(
            model_name='demandamaterial',
            constraint=models.UniqueConstraint(fields=('demanda', 'material'), name='unique_demanda_material'),
        ),
    ]
