# Generated by Django 5.2.11 on 2026-02-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cemiterio', to='enderecos.endereco')),
            ],
            options={
                'verbose_name': 'cemiterio',
                'verbose_name_plural': 'cemiterios',
                'ordering': ['nome'],
            },
        ),
    ]
