# Generated by Django 5.2.11 on 2026-02-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arquivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('assunto', models.CharField(choices=[('BURACO', 'Buraco'), ('ESGOTO', 'Esgoto'), ('ILUMINACAO', 'Iluminacao'), ('LIMPEZA', 'Limpeza'), ('OUTROS', 'Outros')], max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluida'), ('ENCERRADA', 'Encerrada'), ('REJEITADA', 'Rejeitada')], default='ABERTA', max_length=20)),
                ('anexos', models.ManyToManyField(blank=True, related_name='solicitacoes', to='arquivos.arquivo')),
            ],
            options={
                'verbose_name': 'solicitacao',
                'verbose_name_plural': 'solicitacoes',
                'ordering': ['-data'],
            },
        ),
    ]
