# Generated by Django 5.2.11 on 2026-02-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arquivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, default='', max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('honorifico', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField()),
                ('tipo', models.CharField(choices=[('OFICIO', 'Oficio'), ('MEMORANDO', 'Memorando')], max_length=20)),
                ('portaria', models.CharField(blank=True, default='', max_length=255)),
                ('assinante', models.CharField(max_length=255)),
                ('interessado', models.CharField(max_length=255)),
                ('destino', models.CharField(blank=True, default='', max_length=255)),
                ('anexos', models.ManyToManyField(blank=True, related_name='documentos', to='arquivos.arquivo')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['-data'],
            },
        ),
    ]
