name: Integração de codigo

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: '21'

    - name: Build project
      run: mvn clean compile

    - name: Lint with Checkstyle
      run: mvn checkstyle:check

    - name: Run tests
      run: mvn test
