# Generated by Django 5.2.11 on 2026-02-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'endereco',
                'verbose_name_plural': 'enderecos',
            },
        ),
    ]
