# Generated by Django 5.2.11 on 2026-02-08 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cemiterios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jazigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('largura', models.FloatField(blank=True, null=True)),
                ('comprimento', models.FloatField(blank=True, null=True)),
                ('quadra', models.IntegerField()),
                ('rua', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('cemiterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jazigos', to='cemiterios.cemiterio')),
            ],
            options={
                'verbose_name': 'jazigo',
                'verbose_name_plural': 'jazigos',
                'ordering': ['quadra', 'rua', 'lote'],
            },
        ),
    ]
